// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/notification/dao/internal"
)

// sysNotifyDao is the data access object for the table sys_notify.
// You can define custom methods on it to extend its functionality as needed.
type sysNotifyDao struct {
	*internal.SysNotifyDao
}

var (
	// SysNotify is a globally accessible object for table sys_notify operations.
	SysNotify = sysNotifyDao{internal.NewSysNotifyDao()}
)

// Add your custom methods and functionality below.
