// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/bookmark/dao/internal"
)

// bookmarkLabelRelationDao is the data access object for the table bookmark_label_relation.
// You can define custom methods on it to extend its functionality as needed.
type bookmarkLabelRelationDao struct {
	*internal.BookmarkLabelRelationDao
}

var (
	// BookmarkLabelRelation is a globally accessible object for table bookmark_label_relation operations.
	BookmarkLabelRelation = bookmarkLabelRelationDao{internal.NewBookmarkLabelRelationDao()}
)

// Add your custom methods and functionality below.
