// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/bookmark/dao/internal"
)

// bookmarkStatusDao is the data access object for the table bookmark_status.
// You can define custom methods on it to extend its functionality as needed.
type bookmarkStatusDao struct {
	*internal.BookmarkStatusDao
}

var (
	// BookmarkStatus is a globally accessible object for table bookmark_status operations.
	BookmarkStatus = bookmarkStatusDao{internal.NewBookmarkStatusDao()}
)

// Add your custom methods and functionality below.
