// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/bookmark/dao/internal"
)

// userCustomSelectorDao is the data access object for the table user_custom_selector.
// You can define custom methods on it to extend its functionality as needed.
type userCustomSelectorDao struct {
	*internal.UserCustomSelectorDao
}

var (
	// UserCustomSelector is a globally accessible object for table user_custom_selector operations.
	UserCustomSelector = userCustomSelectorDao{internal.NewUserCustomSelectorDao()}
)

// Add your custom methods and functionality below.
