// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/bookmark/dao/internal"
)

// userBookmarkDao is the data access object for the table user_bookmark.
// You can define custom methods on it to extend its functionality as needed.
type userBookmarkDao struct {
	*internal.UserBookmarkDao
}

var (
	// UserBookmark is a globally accessible object for table user_bookmark operations.
	UserBookmark = userBookmarkDao{internal.NewUserBookmarkDao()}
)

// Add your custom methods and functionality below.
