// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/group/dao/internal"
)

// userGroupItemDao is the data access object for the table user_group_item.
// You can define custom methods on it to extend its functionality as needed.
type userGroupItemDao struct {
	*internal.UserGroupItemDao
}

var (
	// UserGroupItem is a globally accessible object for table user_group_item operations.
	UserGroupItem = userGroupItemDao{internal.NewUserGroupItemDao()}
)

// Add your custom methods and functionality below.
