// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/group/dao/internal"
)

// userGroupDao is the data access object for the table user_group.
// You can define custom methods on it to extend its functionality as needed.
type userGroupDao struct {
	*internal.UserGroupDao
}

var (
	// UserGroup is a globally accessible object for table user_group operations.
	UserGroup = userGroupDao{internal.NewUserGroupDao()}
)

// Add your custom methods and functionality below.
