// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/subscription/dao/internal"
)

// sysCurrencyDao is the data access object for the table sys_currency.
// You can define custom methods on it to extend its functionality as needed.
type sysCurrencyDao struct {
	*internal.SysCurrencyDao
}

var (
	// SysCurrency is a globally accessible object for table sys_currency operations.
	SysCurrency = sysCurrencyDao{internal.NewSysCurrencyDao()}
)

// Add your custom methods and functionality below.
