// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/subscription/dao/internal"
)

// userSubscriptionDao is the data access object for the table user_subscription.
// You can define custom methods on it to extend its functionality as needed.
type userSubscriptionDao struct {
	*internal.UserSubscriptionDao
}

var (
	// UserSubscription is a globally accessible object for table user_subscription operations.
	UserSubscription = userSubscriptionDao{internal.NewUserSubscriptionDao()}
)

// Add your custom methods and functionality below.
