// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/user/dao/internal"
)

// sysApiKeyDao is the data access object for the table sys_api_key.
// You can define custom methods on it to extend its functionality as needed.
type sysApiKeyDao struct {
	*internal.SysApiKeyDao
}

var (
	// SysApiKey is a globally accessible object for table sys_api_key operations.
	SysApiKey = sysApiKeyDao{internal.NewSysApiKeyDao()}
)

// Add your custom methods and functionality below.
