// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/stellardex/internal/app/settings/dao/internal"
)

// userSettingsDao is the data access object for the table user_settings.
// You can define custom methods on it to extend its functionality as needed.
type userSettingsDao struct {
	*internal.UserSettingsDao
}

var (
	// UserSettings is a globally accessible object for table user_settings operations.
	UserSettings = userSettingsDao{internal.NewUserSettingsDao()}
)

// Add your custom methods and functionality below.
